site_name: Project Generator

theme: readthedocs

pages:
    - Home: 'index.md'
    - User Guide:
        - 'Getting Started': 'user-guide/getting_started.md'
    - Reference:
        - 'projects.yaml': 'reference/projects.md'

repo_url: https://github.com/project-generator/project_generator/
copyright: Copyright 2015 0xc0170